# AUTO-GENERATED by test/comparison_env/generate_turing_reference.jl
# Regenerate only if the reference models themselves change (see that
# script for why this can't just be a live comparison at test time).
# Captured against Turing v0.45.0 on x86_64-w64-mingw32, 2026-07-07T11:47:23.086
#
# NOTE: the Float32 rows use Float32 data/model literals, but Turing/
# DynamicPPL's getlogjoint promotes internally back to Float64 regardless
# (confirmed directly) — this is NOT an apples-to-apples Float32-compute
# comparison on Turing's side; that gap is itself part of what's measured.
#
# AD backends benchmarked here: ForwardDiff, Mooncake, ReverseDiff, Enzyme (whichever were
# installed + `import`ed when this was generated — see the script for how
# backends are registered).

const TURING_REFERENCE = (
    accuracy = (mu_mean = 1.8912154516199746, mu_std = 0.19037554223674352),
    speed = Dict(
        ("tiny", "Float64_tilde") => (first_call_s=4.8e-6, min_s=4.0e-7, median_s=5.0e-7, mean_s=6.166666666666663e-7, std_s=5.139994185783196e-7),
        ("tiny", "Float32_addlogprob") => (first_call_s=1.88e-5, min_s=6.0e-7, median_s=6.499999999999999e-7, mean_s=8.800000000000004e-7, std_s=8.151158157608335e-7),
        ("tiny", "Float32_tilde") => (first_call_s=3.8e-6, min_s=3.0e-7, median_s=4.0e-7, mean_s=4.833333333333333e-7, std_s=3.553369778338471e-7),
        ("tiny", "Float64_addlogprob") => (first_call_s=4.8e-6, min_s=3.0e-7, median_s=5.0e-7, mean_s=8.533333333333332e-7, std_s=1.5404283625764244e-6),
        ("large", "Float32_addlogprob") => (first_call_s=0.0007908, min_s=0.0005571, median_s=0.0006697999999999999, mean_s=0.0007105966666666667, std_s=0.0001233046143481266),
        ("large", "Float64_tilde") => (first_call_s=0.0008246, min_s=0.0005996, median_s=0.0006896000000000001, mean_s=0.0007078000000000001, std_s=8.322121331023472e-5),
        ("large", "Float64_addlogprob") => (first_call_s=0.00102, min_s=0.0005175, median_s=0.0007548, mean_s=0.0008325333333333335, std_s=0.00022447498337436076),
        ("large", "Float32_tilde") => (first_call_s=0.0007668, min_s=0.0005577, median_s=0.0007264999999999999, mean_s=0.0007164933333333334, std_s=0.00010329833905041605),
    ),
    gradient = Dict(
        ("tiny", "Float64", "ForwardDiff") => (first_call_s=2.04e-5, min_s=4.0e-7, median_s=5.0e-7, mean_s=4.6333333333333333e-7, std_s=6.686751354593717e-8),
        ("tiny", "Float64", "Mooncake") => (first_call_s=4.21e-5, min_s=2.8e-6, median_s=3.2e-6, mean_s=3.3800000000000002e-6, std_s=5.142118173510292e-7),
        ("tiny", "Float32", "Mooncake") => (first_call_s=5.17e-5, min_s=3.2e-6, median_s=3.9e-6, mean_s=5.15e-6, std_s=4.173376207043554e-6),
        ("tiny", "Float32", "Enzyme") => (first_call_s=8.6e-6, min_s=1.3e-6, median_s=1.4e-6, mean_s=1.4233333333333336e-6, std_s=9.352607356658152e-8),
        ("large", "Float64", "Enzyme") => (first_call_s=0.0029374, min_s=0.0014709, median_s=0.0017874499999999999, mean_s=0.0018389799999999998, std_s=0.0002812135676326618),
        ("large", "Float32", "Enzyme") => (first_call_s=0.0019028, min_s=0.0015251, median_s=0.00181025, mean_s=0.001938163333333333, std_s=0.00038193200196689044),
        ("large", "Float32", "ForwardDiff") => (first_call_s=0.0005997, min_s=0.0005172, median_s=0.0007654999999999999, mean_s=0.0008012733333333332, std_s=0.00019434871242945885),
        ("tiny", "Float32", "ReverseDiff") => (first_call_s=0.4168762, min_s=5.63e-5, median_s=5.905e-5, mean_s=6.722333333333332e-5, std_s=1.8529355708942114e-5),
        ("large", "Float64", "Mooncake") => (first_call_s=0.0098284, min_s=0.007205, median_s=0.009530799999999999, mean_s=0.0117069, std_s=0.009320639865670019),
        ("tiny", "Float64", "ReverseDiff") => (first_call_s=0.40765, min_s=3.92e-5, median_s=4.745e-5, mean_s=4.934666666666666e-5, std_s=1.1030857450441195e-5),
        ("tiny", "Float64", "Enzyme") => (first_call_s=1.25e-5, min_s=1.1e-6, median_s=1.1e-6, mean_s=1.1666666666666666e-6, std_s=1.124441112772009e-7),
        ("tiny", "Float32", "ForwardDiff") => (first_call_s=5.7e-6, min_s=4.0e-7, median_s=4.5e-7, mean_s=4.566666666666666e-7, std_s=6.789105539243626e-8),
        ("large", "Float64", "ForwardDiff") => (first_call_s=0.0009058, min_s=0.0005639, median_s=0.0006574, mean_s=0.0007553633333333334, std_s=0.00022864733947845255),
        ("large", "Float32", "Mooncake") => (first_call_s=0.0422538, min_s=0.006979, median_s=0.00958725, mean_s=0.010618720000000002, std_s=0.00655182090827191),
        ("large", "Float64", "ReverseDiff") => (first_call_s=0.1215932, min_s=0.1073471, median_s=0.12813445, mean_s=0.14121662333333332, std_s=0.02693842400895027),
        ("large", "Float32", "ReverseDiff") => (first_call_s=0.1189199, min_s=0.1043457, median_s=0.1263598, mean_s=0.13961748333333332, std_s=0.03979108485670076),
    ),
    nuts = Dict(
        ("large", "Float64") => (first_call_s=1.747468, min_s=1.7059741, median_s=1.9142858, mean_s=2.3406146800000003, std_s=0.8370112900877783),
        ("large", "Float32") => (first_call_s=2.8283734, min_s=1.880368, median_s=2.0061907, mean_s=2.0680029, std_s=0.21748748532650106),
        ("tiny", "Float64") => (first_call_s=2.7556915, min_s=0.0105851, median_s=0.0112021, mean_s=0.01161292, std_s=0.001081837068139191),
        ("tiny", "Float32") => (first_call_s=2.5430313, min_s=0.0103698, median_s=0.0111131, mean_s=0.01166294, std_s=0.0016600637090184217),
    ),
    manyparam = Dict(
        ("Float64", "ForwardDiff") => (first_call_s=0.033342, min_s=0.0243466, median_s=0.0268146, mean_s=0.0272225, std_s=0.002061402015747127),
        ("Float64", "ReverseDiff") => (first_call_s=0.4517857, min_s=0.0087623, median_s=0.014394899999999999, mean_s=0.016895109999999998, std_s=0.012049250872756845),
        ("Float64", "Enzyme") => (first_call_s=0.0027104, min_s=0.0013145, median_s=0.00169685, mean_s=0.00175201, std_s=0.0002732407091886104),
        ("Float64", "Mooncake") => (first_call_s=0.0054887, min_s=0.0031419, median_s=0.00457825, mean_s=0.007281310000000002, std_s=0.011287725256405975),
    ),
    poisson = Dict(
        2000 => (first_call_s=0.0001557, min_s=0.00014, median_s=0.00015995, mean_s=0.00019017000000000003, std_s=7.906346778870449e-5),
        50000 => (first_call_s=0.0041228, min_s=0.0035265, median_s=0.0041895, mean_s=0.004251172, std_s=0.0005052484238592386),
    ),
)
