# AUTO-GENERATED by test/comparison_env/generate_turing_reference.jl
# Regenerate only if the reference models themselves change (see that
# script for why this can't just be a live comparison at test time).
# Captured against Turing v0.45.0 on x86_64-w64-mingw32, 2026-07-07T10:31:26.822
#
# NOTE: the Float32 rows use Float32 data/model literals, but Turing/
# DynamicPPL's getlogjoint promotes internally back to Float64 regardless
# (confirmed directly) — this is NOT an apples-to-apples Float32-compute
# comparison on Turing's side; that gap is itself part of what's measured.
#
# AD backends benchmarked here: ForwardDiff, Mooncake, ReverseDiff, Enzyme (whichever were
# installed + `import`ed when this was generated — see the script for how
# backends are registered).

const TURING_REFERENCE = (
    accuracy = (mu_mean = 1.8912154516199746, mu_std = 0.19037554223674352),
    speed = Dict(
        ("tiny", "Float64_tilde") => (first_call_s=3.8e-6, min_s=6.0e-7, median_s=7.0e-7, mean_s=7.333333333333334e-7, std_s=1.0613372610104645e-7),
        ("tiny", "Float32_addlogprob") => (first_call_s=4.7e-6, min_s=3.0e-7, median_s=4.0e-7, mean_s=4.4666666666666664e-7, std_s=1.0416609195243756e-7),
        ("tiny", "Float32_tilde") => (first_call_s=5.2e-6, min_s=8.0e-7, median_s=9.0e-7, mean_s=9.233333333333336e-7, std_s=8.58359836662575e-8),
        ("tiny", "Float64_addlogprob") => (first_call_s=7.2e-6, min_s=5.0e-7, median_s=1.0e-6, mean_s=8.9e-7, std_s=2.8448380355085003e-7),
        ("large", "Float32_addlogprob") => (first_call_s=0.0011604, min_s=0.0010531, median_s=0.0011313, mean_s=0.0011452566666666666, std_s=6.139967810391491e-5),
        ("large", "Float64_tilde") => (first_call_s=0.0006535, min_s=0.0004552, median_s=0.0007865999999999999, mean_s=0.0007701633333333334, std_s=0.0002287614289337608),
        ("large", "Float64_addlogprob") => (first_call_s=0.000797, min_s=0.0005493, median_s=0.00081185, mean_s=0.0008002500000000002, std_s=0.00015829794855664234),
        ("large", "Float32_tilde") => (first_call_s=0.0010047, min_s=0.0005449, median_s=0.0010575, mean_s=0.0010320366666666668, std_s=0.0001367420917043401),
    ),
    gradient = Dict(
        ("tiny", "Float64", "ForwardDiff") => (first_call_s=5.3e-6, min_s=2.0e-7, median_s=3.0e-7, mean_s=2.9e-7, std_s=5.47722557505166e-8),
        ("tiny", "Float64", "Mooncake") => (first_call_s=4.9e-5, min_s=6.8e-6, median_s=7.850000000000001e-6, mean_s=8.063333333333333e-6, std_s=1.3857609221410933e-6),
        ("tiny", "Float32", "Mooncake") => (first_call_s=5.3e-5, min_s=4.2e-6, median_s=4.5e-6, mean_s=4.6633333333333324e-6, std_s=6.413796193300454e-7),
        ("tiny", "Float32", "Enzyme") => (first_call_s=1.11e-5, min_s=1.6e-6, median_s=1.7e-6, mean_s=1.6833333333333332e-6, std_s=1.1472105098991153e-7),
        ("large", "Float64", "Enzyme") => (first_call_s=0.0023511, min_s=0.001852, median_s=0.0022202999999999997, mean_s=0.0022916266666666673, std_s=0.00028881902689893994),
        ("large", "Float32", "Enzyme") => (first_call_s=0.0027884, min_s=0.0017269, median_s=0.002144, mean_s=0.0022373666666666665, std_s=0.0004515126555933062),
        ("large", "Float32", "ForwardDiff") => (first_call_s=0.000724, min_s=0.0006227, median_s=0.00072665, mean_s=0.0008122899999999999, std_s=0.0002052117264075628),
        ("tiny", "Float32", "ReverseDiff") => (first_call_s=0.3834867, min_s=5.01e-5, median_s=5.215e-5, mean_s=5.522666666666667e-5, std_s=1.0804881825562361e-5),
        ("large", "Float64", "Mooncake") => (first_call_s=0.0137875, min_s=0.0093817, median_s=0.01051925, mean_s=0.019283576666666667, std_s=0.032311852258209116),
        ("tiny", "Float64", "ReverseDiff") => (first_call_s=0.3802464, min_s=9.4e-5, median_s=9.825e-5, mean_s=0.00010009666666666665, std_s=1.2574727894041897e-5),
        ("tiny", "Float64", "Enzyme") => (first_call_s=9.0e-6, min_s=1.1e-6, median_s=1.2e-6, mean_s=1.2366666666666665e-6, std_s=7.183954022841383e-8),
        ("tiny", "Float32", "ForwardDiff") => (first_call_s=8.0e-6, min_s=3.0e-7, median_s=4.0e-7, mean_s=3.8333333333333325e-7, std_s=4.6113303737741396e-8),
        ("large", "Float64", "ForwardDiff") => (first_call_s=0.0008577, min_s=0.0006478, median_s=0.00077105, mean_s=0.0008111766666666667, std_s=0.0001681218824776123),
        ("large", "Float32", "Mooncake") => (first_call_s=0.0140596, min_s=0.0076638, median_s=0.009766750000000001, mean_s=0.0109969, std_s=0.004268385492803153),
        ("large", "Float64", "ReverseDiff") => (first_call_s=0.1706586, min_s=0.0961354, median_s=0.1720895, mean_s=0.17242002666666664, std_s=0.037260408515121614),
        ("large", "Float32", "ReverseDiff") => (first_call_s=0.1592867, min_s=0.1180066, median_s=0.1572836, mean_s=0.15478759333333336, std_s=0.021838979601919536),
    ),
    nuts = Dict(
        ("large", "Float64") => (first_call_s=1.7761412, min_s=1.7503341, median_s=1.8130645, mean_s=1.81992248, std_s=0.06017538146690064),
        ("large", "Float32") => (first_call_s=2.1211421, min_s=1.7936155, median_s=1.8976496, mean_s=1.9154233599999997, std_s=0.12918067827898247),
        ("tiny", "Float64") => (first_call_s=3.1882285, min_s=0.0105803, median_s=0.0113633, mean_s=0.01126306, std_s=0.00039466576111945624),
        ("tiny", "Float32") => (first_call_s=2.9046946, min_s=0.0087199, median_s=0.0101496, mean_s=0.014129520000000001, std_s=0.009747202607774192),
    ),
    manyparam = Dict(
        ("Float64", "ForwardDiff") => (first_call_s=0.0294153, min_s=0.0211484, median_s=0.023102400000000002, mean_s=0.02368469, std_s=0.0019737979032952266),
        ("Float64", "ReverseDiff") => (first_call_s=0.486721, min_s=0.0113056, median_s=0.01343015, mean_s=0.01702332, std_s=0.008811220648373062),
        ("Float64", "Enzyme") => (first_call_s=0.0048191, min_s=0.0017399, median_s=0.00205845, mean_s=0.002149005, std_s=0.0003397358207025292),
        ("Float64", "Mooncake") => (first_call_s=0.0047523, min_s=0.0037106, median_s=0.0046831, mean_s=0.006872784999999999, std_s=0.008367090762547668),
    ),
    poisson = Dict(
        2000 => (first_call_s=0.0002069, min_s=0.0001956, median_s=0.0002046, mean_s=0.00022169399999999998, std_s=3.882878907749364e-5),
        50000 => (first_call_s=0.0043818, min_s=0.0034221, median_s=0.00463205, mean_s=0.0046026420000000005, std_s=0.0005198522867476248),
    ),
)
