# AUTO-GENERATED by test/comparison_env/generate_turing_reference.jl
# Regenerate only if the reference models themselves change (see that
# script for why this can't just be a live comparison at test time).
# Captured against Turing v0.45.0 on x86_64-w64-mingw32, 2026-07-07T08:07:08.617

const TURING_REFERENCE = (
    accuracy = (mu_mean = 1.8912154516199746, mu_std = 0.19037554223674352),
    speed = (tilde_seconds = 0.0188864, addlogprob_seconds = 0.0216123),
)
