# Run ONCE (manually, in this directory's own environment: `julia --project=.
# generate_turing_reference.jl`) to produce `turing_reference.jl` — a plain
# Julia source file of literal numbers that `test/turing_comparison.jl` reads
# back and compares against, WITHOUT ever loading Turing itself.
#
# Why this exists at all: Turing 0.45 (newest released) depends on
# AbstractPPL 0.14.2, but PracticalBayes depends on AbstractPPL 0.15.x (the
# VectorBijectors-based Bijectors API the whole layout system is built on) —
# these two genuinely cannot be loaded in the same Julia process, in any
# environment, with any compat tuning. So instead of a live side-by-side
# comparison, Turing's numbers are captured once here and frozen into a file
# PracticalBayes' own test suite checks against later, in a separate process
# that never touches Turing at all.
#
# Regenerate this file (by rerunning this script in test/comparison_env/)
# only if the reference MODELS themselves change; ordinary PracticalBayes
# code changes should never need this rerun.

using Pkg
Pkg.activate(@__DIR__)

using Turing
using DynamicPPL
using StableRNGs: StableRNG
using Statistics: mean, std
using Distributions: Normal, Exponential, logpdf
using Dates: now

println("Turing version: ", pkgversion(Turing))

# ===========================================================================
# Accuracy reference: conjugate Normal-Normal model, y_i ~ Normal(mu, 1),
# mu ~ Normal(0, 1). Same data-generation seed/procedure as
# test/turing_comparison.jl's PracticalBayes side.
# ===========================================================================
rng = StableRNG(42)
y_accuracy = randn(rng, 30) .+ 2.0

Turing.@model function turing_conjugate(y)
    mu ~ Normal(0, 1)
    for i in eachindex(y)
        y[i] ~ Normal(mu, 1)
    end
end

turing_chain = Turing.sample(StableRNG(1), turing_conjugate(y_accuracy), Turing.NUTS(0.8), 2000; progress=false)
# Turing 0.45 returns a FlexiChains-backed `VNChain`, not the older
# `MCMCChains.Chains` — `chain[:mu]` gives a DimMatrix (iter x chain) that
# plain `vec`/`mean`/`std` handle like any other array once sliced.
turing_mu_draws = vec(Array(turing_chain[:mu])[501:end, :])
turing_mu_mean = mean(turing_mu_draws)
turing_mu_std = std(turing_mu_draws)

println("Turing conjugate posterior: mean=", turing_mu_mean, " std=", turing_mu_std)

# ===========================================================================
# Speed reference: observe-heavy model, 10_000 scalar observations. Times
# Turing's plain `~` loop and its `@addlogprob!` escape hatch, both via
# `Turing.VarInfo`/model-call (same mechanism DynamicPPL uses internally, no
# sampling needed since we're only measuring one log-density evaluation's
# cost, repeated).
# ===========================================================================
rng2 = StableRNG(7)
y_speed = randn(rng2, 10_000)

Turing.@model function turing_tilde_many_obs(y)
    mu ~ Normal(0, 1)
    sigma ~ Exponential(1)
    for i in eachindex(y)
        y[i] ~ Normal(mu, sigma)
    end
end

Turing.@model function turing_addlogprob_many_obs(y)
    mu ~ Normal(0, 1)
    sigma ~ Exponential(1)
    Turing.@addlogprob! sum(logpdf.(Normal(mu, sigma), y))
end

turing_tilde_model = turing_tilde_many_obs(y_speed)
turing_addlogprob_model = turing_addlogprob_many_obs(y_speed)
# `Turing.VarInfo` isn't directly exported in this version; the underlying
# type lives in DynamicPPL (a Turing dependency, added here directly so we
# can reach it).
turing_vi = DynamicPPL.VarInfo(turing_tilde_model)
turing_vi_add = DynamicPPL.VarInfo(turing_addlogprob_model)

# warmup (compilation) before timing
turing_tilde_model(turing_vi)
turing_addlogprob_model(turing_vi_add)

t_turing_tilde = @elapsed for _ in 1:200
    turing_tilde_model(turing_vi)
end
t_turing_addlogprob = @elapsed for _ in 1:200
    turing_addlogprob_model(turing_vi_add)
end

println("Turing tilde timing (200 evals): ", t_turing_tilde, "s")
println("Turing @addlogprob! timing (200 evals): ", t_turing_addlogprob, "s")

# ===========================================================================
# Write the reference file. Plain Julia literals only — no Turing types
# leak into it, so it's safe to `include` from an environment that has never
# heard of Turing.
# ===========================================================================
out_path = joinpath(@__DIR__, "..", "turing_reference.jl")
open(out_path, "w") do io
    println(io, "# AUTO-GENERATED by test/comparison_env/generate_turing_reference.jl")
    println(io, "# Regenerate only if the reference models themselves change (see that")
    println(io, "# script for why this can't just be a live comparison at test time).")
    println(io, "# Captured against Turing v$(pkgversion(Turing)) on $(Sys.MACHINE), $(now())")
    println(io)
    println(io, "const TURING_REFERENCE = (")
    println(io, "    accuracy = (mu_mean = ", turing_mu_mean, ", mu_std = ", turing_mu_std, "),")
    println(io, "    speed = (tilde_seconds = ", t_turing_tilde, ", addlogprob_seconds = ", t_turing_addlogprob, "),")
    println(io, ")")
end
println("Wrote reference to: ", out_path)
