# A representative slice of TuringPosteriorDB.jl models
# (https://github.com/JasonPekos/TuringPosteriorDB.jl/tree/main/src/models),
# ported to PracticalBayes' `@model` syntax. Chosen to cover the model
# FAMILIES present in the corpus (see devlog for the full family list) with
# minimal editing per model, exercising: plain scalar `~` (Rate_1),
# `filldist`/array-observe regression (blr, earn_height), hierarchical
# MvNormal with `Fill`-equivalent (eight_schools_centered), `:=` computed
# quantities feeding back into a further `~`/`.~` (dugongs,
# eight_schools_noncentered), discrete-likelihood GLMs with log/logit link
# reparameterizations (GLM_Poisson, wells_dae), and `Flat`/`FlatPos` improper
# priors (kidscore_interaction, earn_height, wells_dae).
#
# PosteriorDB's actual datasets aren't fetched here (would need
# TuringPosteriorDB.jl itself, a Turing-ecosystem package that can't coexist
# with PracticalBayes in one process — see test/comparison_env's whole
# reason for existing). Each model instead gets synthetic data matching its
# real argument shapes/types, generated by `make_*_data` below — sufficient
# to prove PracticalBayes correctly RUNS this model structure (every
# distribution/syntax feature it uses) with a real logdensity + gradient,
# which is the actual point of this corpus pass. Exact posterior replication
# against PosteriorDB's real data is a separate, heavier undertaking (would
# need the real data AND a Turing-side reference run) not attempted here.

using PracticalBayes
using Distributions
using Distributions: logistic
using LinearAlgebra: I, Diagonal
using Random

# ===========================================================================
# Rate_1 — simplest possible model: one Beta-Binomial conjugate pair.
# ===========================================================================
@model function Rate_1_model(n, k)
    theta ~ Beta(1, 1)
    k ~ Binomial(n, theta)
end
make_Rate_1_data(seed) = (n=20, k=7)

# ===========================================================================
# blr — Bayesian linear regression: filldist prior + MvNormal array-observe.
# ===========================================================================
@model function blr_model(N, D, X, y)
    beta ~ filldist(Normal(0, 10), D)
    sigma ~ Truncated(Normal(0, 10), 0, Inf)
    y ~ MvNormal(X * beta, sigma^2 * I)
end
function make_blr_data(seed)
    rng = Random.Xoshiro(seed)
    N, D = 30, 4
    X = randn(rng, N, D)
    true_beta = randn(rng, D)
    y = X * true_beta .+ randn(rng, N) .* 0.5
    return (N=N, D=D, X=X, y=y)
end

# ===========================================================================
# eight_schools_centered — classic hierarchical model: MvNormal with a
# constant-mean vector (`Fill(mu, J)` -> `fill(mu, J)`, no need for the
# FillArrays package itself, plain `fill` produces the same MvNormal mean).
# ===========================================================================
@model function eight_schools_centered_model(J, y, sigma)
    tau ~ Truncated(Cauchy(0, 5), 0, Inf)
    mu ~ Normal(0, 5)
    theta ~ MvNormal(fill(mu, J), sqrt(tau) * I)
    y ~ MvNormal(theta, Diagonal(sqrt.(sigma)))
end
function make_eight_schools_data(seed)
    rng = Random.Xoshiro(seed)
    J = 8
    sigma = abs.(randn(rng, J)) .* 5 .+ 5
    true_theta = randn(rng, J) .* 5
    y = true_theta .+ randn(rng, J) .* sqrt.(sigma)
    return (J=J, y=y, sigma=sigma)
end

# ===========================================================================
# eight_schools_noncentered — same model, non-centered parameterization:
# `:=` used to build a DERIVED vector (`theta`) from a standard-normal
# `theta_trans` draw, which then flows into the observe MvNormal.
# ===========================================================================
@model function eight_schools_noncentered_model(J, y, sigma)
    tau ~ Truncated(Cauchy(0, 5), 0, Inf)
    mu ~ Normal(0, 5)
    theta_trans ~ MvNormal(fill(0.0, J), I)
    theta := [tau * s + mu for s in theta_trans]
    y ~ MvNormal(theta, Diagonal(sqrt.(sigma)))
end

# ===========================================================================
# dugongs — nonlinear (power-law) regression mean; `:=` used purely for
# reporting derived quantities (sigma, U3) that don't feed back into any
# further `~`, exercising that `:=` doesn't require downstream conditioning
# to be useful.
# ===========================================================================
@model function dugongs_model(N, x, Y)
    alpha ~ Normal(0, 1000)
    beta ~ Normal(0, 1000)
    lambda ~ Uniform(0.5, 1.0)
    tau ~ Gamma(1.0e4, 1.0e-4)
    sigma := 1 / sqrt(tau)
    Y ~ MvNormal(alpha .- beta .* lambda .^ x, sigma^2 .* I)
end
function make_dugongs_data(seed)
    rng = Random.Xoshiro(seed)
    N = 27
    x = collect(1.0:N)
    true_alpha, true_beta, true_lambda = 2.5, 1.5, 0.9
    Y = true_alpha .- true_beta .* true_lambda .^ x .+ randn(rng, N) .* 0.1
    return (N=N, x=x, Y=Y)
end

# ===========================================================================
# GLM_Poisson — discrete-likelihood GLM with a log-linked rate (`LogPoisson`)
# and a cubic-in-year mean; also exercises `:=` computing a reported
# (non-conditioned) `lambda = exp.(log_lambda)`.
# ===========================================================================
@model function GLM_Poisson_model(n, C, year; year_squared=year .^ 2, year_cubed=year .^ 3)
    alpha ~ Uniform(-20, 20)
    beta1 ~ Uniform(-10, 10)
    beta2 ~ Uniform(-10, 10)
    beta3 ~ Uniform(-10, 10)
    log_lambda := alpha .+ beta1 .* year .+ beta2 .* year_squared .+ beta3 .* year_cubed
    C .~ LogPoisson.(log_lambda)
    lambda := exp.(log_lambda)
end
function make_GLM_Poisson_data(seed)
    rng = Random.Xoshiro(seed)
    n = 20
    year = collect(range(-1.0, 1.0; length=n))
    true_alpha, true_beta1 = 1.0, 0.5
    C = Float64.(rand.(rng, Poisson.(exp.(true_alpha .+ true_beta1 .* year))))
    return (n=n, C=C, year=year)
end

# ===========================================================================
# kidscore_interaction — Flat improper priors via filldist(Flat(), 4),
# array-observe interaction regression.
# ===========================================================================
@model function kidscore_interaction_model(N, kid_score, mom_iq, mom_hs)
    inter = mom_hs .* mom_iq
    beta ~ filldist(Flat(), 4)
    sigma ~ Truncated(Cauchy(0, 2.5), 0, Inf)
    kid_score ~ MvNormal(beta[1] .+ beta[2] .* mom_hs .+ beta[3] .* mom_iq .+ beta[4] .* inter, sigma^2 * I)
end
function make_kidscore_data(seed)
    rng = Random.Xoshiro(seed)
    N = 40
    mom_hs = Float64.(rand(rng, Bool, N))
    mom_iq = randn(rng, N) .* 15 .+ 100
    inter = mom_hs .* mom_iq
    true_beta = [20.0, 5.0, 0.5, -0.05]
    kid_score = true_beta[1] .+ true_beta[2] .* mom_hs .+ true_beta[3] .* mom_iq .+ true_beta[4] .* inter .+
                randn(rng, N) .* 10
    return (N=N, kid_score=kid_score, mom_iq=mom_iq, mom_hs=mom_hs)
end

# ===========================================================================
# earn_height — Flat/FlatPos priors, minimal regression (2-parameter beta).
# ===========================================================================
@model function earn_height_model(N, earn, height)
    beta ~ filldist(Flat(), 2)
    sigma ~ FlatPos(0.0)
    earn ~ MvNormal(beta[1] .+ beta[2] .* height, sigma^2 * I)
end
function make_earn_height_data(seed)
    rng = Random.Xoshiro(seed)
    N = 50
    height = randn(rng, N) .* 3 .+ 66
    true_beta = [-10000.0, 500.0]
    earn = true_beta[1] .+ true_beta[2] .* height .+ randn(rng, N) .* 5000
    return (N=N, earn=earn, height=height)
end

# ===========================================================================
# wells_dae — logistic-regression GLM (BernoulliLogit, a Distributions.jl
# builtin) with Flat priors, matrix-valued design via `hcat`.
# ===========================================================================
@model function wells_dae_model(N, switched, dist, arsenic, educ)
    dist100 = dist ./ 100
    educ4 = educ ./ 4.0
    x = hcat(dist100, arsenic, educ4)
    alpha ~ Flat()
    beta ~ filldist(Flat(), 3)
    switched .~ BernoulliLogit.(alpha .+ x * beta)
end
function make_wells_data(seed)
    rng = Random.Xoshiro(seed)
    N = 60
    dist = abs.(randn(rng, N)) .* 50 .+ 20
    arsenic = abs.(randn(rng, N)) .* 2 .+ 1
    educ = rand(rng, 0:12, N)
    true_alpha, true_beta = 0.5, [-0.01, -0.3, 0.05]
    x = hcat(dist ./ 100, arsenic, educ ./ 4.0)
    p = logistic.(true_alpha .+ x * true_beta)
    switched = Float64.(rand(rng, N) .< p)
    return (N=N, switched=switched, dist=dist, arsenic=arsenic, educ=educ)
end
